
data:
    transition-duration: 500

inactive_opacity: 0

increments:
    z: 5000

slides:
    - content: |
        Alexandre Rock Ancelelet

        PHP / Symfony trainer

        Follow me `@pierstoval`Â **(everywhere)**

    - content_type: html
      content: |
        <h1>Comment j'ai <span style="text-decoration: line-through;">digitalisÃ©</span> numÃ©risÃ© le jeu de rÃ´le ?</h1>

    - content: |
        D'abord, Jean-Pierre, une question :

        **C'est quoi le Jeu de rÃ´le ? ğŸ¤—**

    - content_type: html
      content: |
        <h1 style="font-size: 3.5em;">ğŸº + ğŸ• + ğŸ“ + ğŸ²</h1>
        <h1 style="font-size: 3em;">=</h1>
        <h1 style="font-size: 3em;">Fun</h1>

    - content: |
        J'ai pris un jeu de rÃ´le papier.

        https://www.esteren.org/

        ![Logo Esteren](img/esteren_logo.png)

    - content: |
        Il m'a fallu lire TOUT le livre: 350 pages

        ![Livre 1](img/livre1.jpg)

    - content_type: html
      content: |
        <p>Super !<br>J'ai appris comment crÃ©er un personnage !</p>

        <div style="font-size: 3em;">ğŸ‘§Â ğŸ‘¨</div>

        <div style="font-size: 3em;">ğŸ‰</div>

    - content: |
        J'ai cherchÃ© un bon moyen d'en crÃ©er plus rapidement.

        Parce que se taper la lecture de 50 pages de rÃ¨gles Ã  chaque fois, c'est...

        ğŸ’¤ğŸ’¤...

    - content: |
        J'ai dÃ©couvert le site [LaÂ ScÃ©nariothÃ¨que](http://www.scenariotheque.org/)

        TrÃ¨s cool !

        C'est une plateforme pour les "rÃ´listes" avec beaucoup d'aides de jeu, de feuilles de personnage prÃ©calculÃ©es !

    - content_type: html
      content: |
        <p>Des fichiers DOCX, ODT, XLS, PDFÂ <small><small>(50MoÂ leÂ PDF...)</small></small>, JPG...</p>

        <p>Plein d'outils !</p>

    - content: 'Et puis...'

    - content_type: html
      content: '<div style="font-size: 5em;">ğŸ’¥</div>'

    - content: |
        En fait, aucun de cesÂ fichiersÂ neÂ correspondait.

        Pas compatible, pas performant, pas pratique, pas facile Ã  comprendre.

        Bref.

        Pas adaptÃ©.

        <small>(Comme nos projets legacy)</small>

    - content: |
        Je me suis donc inspirÃ© des plus grands dÃ©veloppeurs
    - content: |
        ![Fabien](img/fabpot.png)

    - content: |
        J'ai crÃ©Ã© un outil open-source, ilÂ yÂ aÂ 6Â ans.

        UtilisÃ© tous les jours par des "rÃ´listes" qui jouent Ã  ce jeu. PrÃ¨s 3400 personnages enregistrÃ©s.

        Dispo ici : https://github.com/Esteren/CorahnRinV1

        (C'est du PHP tout pourri)

    - content: '![capt1](img/capt1.png)'
    - content: '![capt1](img/capt2.png)'
    - content: |
        ![capt1](img/capt3.png)

        (ceci est un fichier pdf auto-gÃ©nÃ©rÃ©)

    - content: '![map](img/map.png)'


    - content: |
        Aujourd'hui, il est en train d'Ãªtre complÃ¨tement refait.

        Avec plein d'outils cools, performants, propres, maintenables.

    - content: |
        Des outils ce que vous dÃ©couvrez en meetup, en convention, dans votre boulot, sur Github, sur Twitter,
        sur des blogs...

    - content_type: html
      content: |
        <p>Symfony, Twig, Doctrine, LeafletJS, Gulp, Behat, PHPUnitÂ <small>(les tests, c'est cool)</small>, et tant
        d'autres</p>

    - content: |
        Des outils sans lesquels personne ne serait lÃ  aujourd'hui Ã  cette confÃ©rence.

    - content: |
        Des outils sans lequels nous ne serions pas de bons dÃ©veloppeurs aujourd'hui.

    - content_type: html
      content: |
        <p>J'ai pu dÃ©velopper moi-mÃªme des outils:</p>

        <ul>
          <li style="text-align:left;"><a href="https://github.com/Orbitale/CmsBundle">https://github.com/Orbitale/CmsBundle</a></li>
          <li style="text-align:left;"><a href="https://github.com/Orbitale/ImageMagickPHP">https://github.com/Orbitale/ImageMagickPHP</a></li>
          <li style="text-align:left;"><a href="https://github.com/Orbitale/Gulpfile">https://github.com/Orbitale/Gulpfile</a></li>
          <li style="text-align:left;"><a href="https://github.com/Pierstoval/CharacterManagerBundle">https://github.com/Pierstoval/CharacterManagerBundle</a></li>
        </ul>

    - content_type: html
      content: |

        <p>Alors un grand merci Ã  tous les contributeurs de projets libres et open-source.</p>

        <small>fabpot, nicolas-grekas, webmozart, Tobion, xabbuh, stof, Seldaek, vicb, schmittjoh, kriswallsmith, jakzal,
        dunglas, weaverryan, pborreli, romainneutron, aitboudad, lyrixx, javiereguiluz, stloyd, lsmith77, wouterj,
        ogizanagi, chalasr, hason, igorw, beberlei, jmikola, jfsimon, HeahDude, hhamon, saro0h, etc...</small>

    - content_type: html
      content: |
        <p style="font-size: 3em;">Et merci Ã  vous.</p>
